### ISSUE TITLE
No ReaderType or WriterType could be detected. 

### ISSUE THREAD

**Issue by markwillow** [eighty9nine/filament-excel-import#17]
No ReaderType or WriterType could be detected. Make sure you either pass a valid extension to the filename or pass an explicit type.

I am getting this error message even though I am using .xlxs, .xls or .csv file.

**Comment by markwillow** [comment]
This is no longer an issue. It happens due to the new update with Laravel. So, make sure to update your component too.

**Comment by irfanandratama** [comment]
> This is no longer an issue. It happens due to the new update with Laravel. So, make sure to update your component too.

How do you resolve it?

**Comment by markwillow** [comment]
I guess this is an on-going issue. Can someone look at this?

**Comment by eighty9nine** [comment]
Please provide details on how to reproduce the issue

**Comment by eighty9nine** [comment]
Closed due to no update on issue

**Comment by caweb** [comment]
I got the same error
I have Laravel 11, Filament v3.2.113 installed

I select an excel file and press the upload button and then this screen appears

![image](https://github.com/user-attachments/assets/f6f3ee1e-ce75-4ac6-afe8-6e89dfd830b9)
