### ISSUE TITLE
Download Sample File?

### ISSUE THREAD

**Issue by fhsdmhacc** [eighty9nine/filament-excel-import#26]
Hello,

I hope this message finds you well. I am currently working with your plugin and noticed that Filament’s default import functionality includes an option to download a sample file for reference. I was wondering if your plugin has a similar feature that allows users to download a sample file.

If this feature is available, could you please provide details on how to access it? If not, do you have any recommendations for handling sample files within the context of your plugin?

Thank you for your assistance.

![Screenshot 2024-09-09 142129 githubissues](https://github.com/user-attachments/assets/1a2cb59a-96c8-4593-a885-1e0d23b59e00)

**Comment by eighty9nine** [comment]
Have you found a solution? @fhsdmhacc

**Comment by avinmaster** [comment]
Up!

**Comment by fhsdmhacc** [comment]
@eighty9nine yeah, i add custom button to list page. i install plugin [pxlrbt](https://github.com/pxlrbt/filament-excel) for CountryCodeExport

![carbon (5)](https://github.com/user-attachments/assets/8c31ffd0-fe7e-4614-8ad7-af5c4e2e96a7)

**Comment by fhsdmhacc** [comment]
or you can see my full code in another issue https://github.com/eighty9nine/filament-excel-import/issues/27

**Comment by eighty9nine** [comment]
In the latest release you can enable your users to download sample file. Please find in the [Documentation](https://github.com/eighty9nine/filament-excel-import/tree/3.1.8#sample-excel-file)
