### ISSUE TITLE
Unable to retrieve the file_size for file at location: 1

### ISSUE THREAD

**Issue by fhsdmhacc** [eighty9nine/filament-excel-import#27]
First of all, thank you for providing this wonderful plugin!
Every time I click import button, I get the following error before the file is even uploaded.
I receive the error message "Unable to retrieve the file_size for file at location: 1" even before the file is uploaded.
Any guidance or assistance with this issue would be greatly appreciated. Thank you in advance for your help!

Here is my code:
![carbon (6)](https://github.com/user-attachments/assets/965f14c2-485a-4db1-a1a8-3a758ac14590)

**Comment by caweb** [comment]
I got the same error, I am using.
Laravel 11, Filament v3.2.113

after press the upload button this screen appears

![image](https://github.com/user-attachments/assets/4351fae3-5ecf-4b70-a92d-7e493fb52901)

**Comment by fhsdmhacc** [comment]
i deleted folder 1 from storage/app/public, somehow it worked.
I solved it by changing the directory path to uuid.

**Comment by caweb** [comment]
> i deleted folder 1 from storage/app/public, somehow it worked. I solved it by changing the directory path to uuid.

Thank you for your response. 
Could you share, the code o where did you change the directory path to uuid?

**Comment by fhsdmhacc** [comment]
have you tried deleting folder 1 in storage/app/public? and does it work?

**Comment by fhsdmhacc** [comment]
https://spatie.be/docs/laravel-medialibrary/v11/advanced-usage/using-a-custom-directory-structure

from documentation

**Comment by caweb** [comment]
> have you tried deleting folder 1 in storage/app/public? and does it work?

yes it works

**Comment by caweb** [comment]
> https://spatie.be/docs/laravel-medialibrary/v11/advanced-usage/using-a-custom-directory-structure
> 
> from documentation

thank you

**Comment by eighty9nine** [comment]
Thanks @fhsdmhacc for the solution 👍🏽
