### ISSUE TITLE
How to get additional data from Custom Importer

### ISSUE THREAD

**Issue by roylisto** [eighty9nine/filament-excel-import#28]
I have a custom importer, how to get the additional data there?

**Comment by lovemintblue** [comment]
> I have a custom importer, how to get the additional data there?

Did you solve it?

**Comment by roylisto** [comment]
> > I have a custom importer, how to get the additional data there?
> 
> Did you solve it?

not yet

**Comment by eighty9nine** [comment]
Some features are `DefaultImporter`,  in order to get all features in a customer importer, after you create your importer, please extend the `DefaultImporter`

**Comment by cquiroscrc** [comment]
Good morning, please help me.

After extending , the data still is missing in the extended class
I use:
```
->use( ExcelDosimetroImport::class)
->beforeUploadField([
                    TextInput::make('dosimetro_control')
                        ->numeric()
                        ->label('Dosimetro Control')
                        ->suffixIcon('heroicon-m-globe-alt')
                        ->suffixIconColor('success')
                        ->required(),
                    TextInput::make('dosimetro_control_backup')
                        ->numeric()
                        ->label('Dosimetro Control - Backup')
                        ->suffixIcon('heroicon-m-globe-alt')
                        ->suffixIconColor('success')
                        ->required(),
                ])
->afterImport(function (array $data, $livewire, $excelImportAction) {
                    $dosimetro_control = $data['dosimetro_control'];
                    $dosimetro_control_backup = $data['dosimetro_control_backup'];
                    $original_filename = $livewire;
                    // When adding the additional data, the data will be merged with
                    // the row data when inserting into the database
                    $excelImportAction->additionalData([
                        'dosimetro_control' => $dosimetro_control,
                        'dosimetro_control_backup' => $dosimetro_control_backup,
                        'original_filename' => $original_filename
                    ]);
                })
```
and in the ExcelDosimetroImport:
```
protected array $additionalData = [];

    public function setAdditionalData(array $additionalData): void
    {
        $this->additionalData = $additionalData;
    }

    public function collection(Collection $collection)
        {

        // Acceder a los datos adicionales
        $dosimetro_control = $this->additionalData['dosimetro_control'] ?? null;
        $dosimetro_control_backup = $this->additionalData['dosimetro_control_backup'] ?? null;
        $original_filename = $this->additionalData['original_filename'] ?? null;

```
                
What is the correct way of extending it?

**Comment by eighty9nine** [comment]
@cquiroscrc  Can you please further explain what you are trying to achieve, what is your use case?

**Comment by lovemintblue** [comment]
> > I have a custom importer, how to get the additional data there?
> 
> Did you solve it?

I have an operation that solves this

**Comment by lovemintblue** [comment]
> > > 我有一个自定义导入器，如何从那里获取附加数据？
> > 
> > 
> > 你解决了吗？
> 
> 还没有

I have an operation that solves this

**Comment by cquiroscrc** [comment]
> eighty9nine

Hello Sir.
I'm trying to send to ExcelDosimetroImport the data in ->afterImport event using the recomendation of extending the class. If you want i can upload the two files with full code.

**Comment by eighty9nine** [comment]
@cquiroscrc I was asking, what problem does sending ExcelDosimetroImport the data in ->afterImport event solve? I am trying to understand the problem you want solve... I could perhaps suggest a more efficient approach

**Comment by cquiroscrc** [comment]
The problem trying to solve is to pass to the model  the original filename uploaded and two values coming from two text inputs, one text input stores a dosimeter code and the other , the dosimeter backup code.
The text input are part of beforeUploadField()

**Comment by lovemintblue** [comment]
> The problem trying to solve is to pass to the model the original filename uploaded and two values coming from two text inputs, one text input stores a dosimeter code and the other , the dosimeter backup code. The text input are part of beforeUploadField()

I appended it to the cache through the cache method, took the cache in the import file, and cleared the cache after the operation was completed.

**Comment by eighty9nine** [comment]
Can you try using `beforeImport()` instead? The additional data is passed to the importer before import, with the logic being, the additional data will be insert into the database,.

**Comment by ChrisToxz** [comment]
> @cquiroscrc I was asking, what problem does sending ExcelDosimetroImport the data in ->afterImport event solve? I am trying to understand the problem you want solve... I could perhaps suggest a more efficient approach

I might have a similar case that I don't get solved.
My situation: Model A hasMany Model B's.
Model A is created ONCE in my custom import, this is done with the `BeforeImport` event.
Model A needs data from both the file and from the form. 

The file contains both data that needs to be used once, and rows that will be imported as Model B.

Using `additionalData()` is no option because this will be used for each row, however I only need the data ones.
And I think the issue above is similar, we would like to pass form inputs to the custom import class.

**Comment by eighty9nine** [comment]
I have understood now @ChrisToxz , I have pushed a new release, hopefully solving the problem with `customImportData`, this data will be available in the custom import, but will not be merged with data for each row. You can find it documented in the [form customisation section](https://github.com/eighty9nine/filament-excel-import#form-customisation)

![image](https://github.com/user-attachments/assets/4ed807bd-4586-47a5-b82f-26bc115f2283)

**Comment by ChrisToxz** [comment]
It works, just not sure why it needs to be in the `DefaultImporter`
I was using `ToModel()` and now when I extend the `collection()` of the `DefaultImporter` runs as well.
Easy to overwrite, but not sure if it is great for the DX.

You have any idea how I could return an error from the importer back to the frontend?
I'm using data of the imported file and from the from in order to conclude something. Not always it is allowed to continue, and should return an error to the user.

**Comment by sng82** [comment]
I found lots of helpful info above, but no complete answer. I'm leaving this here hoping it might be helpful to the next confused soul who stumbles upon the same issue...

Lets assume you have a custom import file (`MyCustomImport.php`) and have extended `ExcelImportAction::make()` in the  `getHeaderActions()` array to include additional form inputs (via either `->beforeInput()` or `->afterInput()`. You want to make the  data from these form inputs available within your custom import file.

Your list page might look a bit like this:

```php

//app\Filament\Resources\[MyResource]\pages\ListMyResource.php

...
use EightyNine\ExcelImport\ExcelImportAction;
...
classMyResources extends ListMyResources
{
    ...
    protected function getHeaderActions(): array
    {
        return [
            ...
            ExcelImportAction::make()
                             ->use(MyCustomImport::class)
                             ->beforeUploadField([
                                 DatePicker::make('important_date')
                                           ->native(false)
                                           ->default(Carbon::now())
                                           ->displayFormat('D, jS M, Y')
                                           ->closeOnDateSelection()
                                           ->required(),
                             ])
                             ->beforeImport(function (array $data, $livewire, $excelImportAction) {
                                 $excelImportAction->customImportData([
                                     'important_date' => $data['important_date'],
                                     'created_by'     => auth()->id(),
                                 ]);
                             }),
            ...
        ]
    ...
}

``` 

You'll want to make the following changes to your Import file:

```diff

//app\Imports\MyCustomImport.php    

...
- use Maatwebsite\Excel\Concerns\ToCollection;
+ use EightyNine\ExcelImport\DefaultImport;
...
- class MyCustomImport implements ToCollection
+ class MyCustomImport extends DefaultImport
{
    ...
    public function collection(Collection $collection)
    {
        ...
        // $this->customImportData is an array containing 'created_by' and 'important_date'. Dump and die here to prove it works.
        dd($this->customImportData);
        ...
    }  
}
```

The downside of doing this is that it completely changes the formatting of `$collection` (the contents of the object used to be an indexed array, but now becomes an associative array). I'm still trying to work out why, and if I can prevent this happening. I'll update here if I can make any sense of it. @eighty9nine - can you shed any light?
