### ISSUE TITLE
Feature Request: Ability to use on Relation Manager

### ISSUE THREAD

**Issue by Kenneth-Inkum** [eighty9nine/filament-excel-import#3]
Thank you for this nifty plugin. I would love if you could add ability to use on Relation Manager to import related data.

**Comment by eighty9nine** [comment]
> Thank you for this nifty plugin. I would love if you could add ability to use on Relation Manager to import related data.

Can you provide a sample use case so I can get a better understanding of the requested feature

**Comment by renatoaldana** [comment]
> > Thank you for this nifty plugin. I would love if you could add ability to use on Relation Manager to import related data.
> 
> Can you provide a sample use case so I can get a better understanding of the requested feature

For example, I have a  ClassResource, with a Students RelationManager. I need to import students into their classes through the relation manager, not from the StudentResource.

`\App\Filament\Resources\ClassResource\RelationManagers\EightyNine\ExcelImport\ExcelImportAction`

Excel export plugin is usable in relation manager: https://filamentphp.com/plugins/pxlrbt-excel

**Comment by robschmitt** [comment]
+1 for this enhancement request. There are currently no options in Filament 3 for running imports through a RelationManager.

**Comment by rvzug** [comment]
I also would like to suggest this feature

Most simple use case would be, if you create a ```RelationManager``` and add a ExcelImportAction to the table-method, the headerActions():

```php
class StudentsRelationManager extends RelationManager
{

 public function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('identifier')
                    ->label('Code'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),

                ExcelImportAction::make()
                    ->use(StudentsImport::class)

            ])
            ->actions([
                 //
            ]);
    }

}
```
In this case, now it will return a ExcelImportAction::table() method not found exception.
Filament has seperated the "actions" and "table actions" into different classes.

**Comment by eighty9nine** [comment]
This has been implemented in the latest update

**Comment by pschilly** [comment]
This does not seem to function as expected? I am using a Relationship Manager "Page" instead of the tab...  When I attempt the import - it tries to import to the related model instead of the pivot table - thoughts?
