### ISSUE TITLE
Error The Mounted Actions Data When Import

### ISSUE THREAD

**Issue by fhsdmhacc** [eighty9nine/filament-excel-import#35]
I just deployed my web to a VPS service with cpanel. but when importing I get an error as shown.
![image](https://github.com/user-attachments/assets/21edbe90-9f43-4106-b4c3-69ad71c252a8)

I use almalinux OS and have also set the permission for the storage folder to 775 with the command “sudo chmod -R 775”, it still doesn't work.
![carbon (6)](https://github.com/user-attachments/assets/c1be99fb-1f62-433d-a246-f485f74a6e35)

**Comment by abdrahmaan** [comment]
any updates ?
