### ISSUE TITLE
I am getting error after installation.

### ISSUE THREAD

**Issue by jiten14** [eighty9nine/filament-excel-import#4]
I followed your guide as described, I am getting following Error. Please help me.

Class "App\Filament\Resources\UserResource\Pages\EightyNine\ExcelImport\ExcelImportAction" not found

**Comment by jiten14** [comment]
namespace App\Filament\Resources\UserResource\Pages;



use App\Filament\Resources\UserResource;

use Filament\Actions;

use Filament\Resources\Pages\ListRecords;



class ListUsers extends ListRecords

{

    protected static string $resource = UserResource::class;



    protected function getHeaderActions(): array

    {

        return [

            EightyNine\ExcelImport\ExcelImportAction::make()

                ->color("primary"),

            Actions\CreateAction::make(),

        ];

    }

}

**Comment by abewartech** [comment]
```
\EightyNine\ExcelImport\ExcelImportAction::make()
                ->color("primary"),
```

add \ in the front EightyNine
