### ISSUE TITLE
Feature: Use validation rules

### ISSUE THREAD

**Issue by grafst** [eighty9nine/filament-excel-import#5]
Reuse the validation rules from the create resource...
would this be possible?

**Comment by eighty9nine** [comment]
Unfortunately due the package limitations, we cannot use form field validations in the package! 

This has been added still, please update the package and see on the documentation validation section! There is still more work to be done so any feedback is appreciated!

**Comment by grafst** [comment]
> This has been added still, please update the package and see on the documentation validation section! There is still more work to be done so any feedback is appreciated!

awesome!
yes, will check it out sometime
