### ISSUE TITLE
Modify the modal import and add forms or form items

### ISSUE THREAD

**Issue by eighty9nine** [eighty9nine/filament-excel-import#6]

**Comment by mohaaosman** [comment]
Hi, great plugin!,

When will this be published?

**Comment by eighty9nine** [comment]
A new version is scheduled to be released by 8th December. It will have
- Import modal customization
- Imports on relation managers
- Translations

**Comment by koyanyaroo** [comment]
@eighty9nine Great job on the plugin! Looking forward to the next one! 👍

**Comment by aeq-dev** [comment]
Any update :eyes:

**Comment by eighty9nine** [comment]
Form customisation has been and is available in the docs
