### ISSUE TITLE
Access to import class file name?

### ISSUE THREAD

**Issue by mclgms** [eighty9nine/filament-excel-import#7]
Congratulations on the plugin.
When we implement the import class we have access to the Collection, but which object do I have access to the file? Do I need to implement some interface for this?

**Comment by urufudev** [comment]
> Congratulations on the plugin. When we implement the import class we have access to the Collection, but which object do I have access to the file? Do I need to implement some interface for this?

Hi 
Have you resolved the issue? 🤔

**Comment by DiGiTransf** [comment]
Same issue: I have to save uploaded file names within updated record in the database, but no way to access file name property of upload class

**Comment by eighty9nine** [comment]
This can be found in the documentation. The entire file object can be found inside `beforeImport()` and `afterImport()` hooks, you can play around with it from there!
