### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by kristijanw** [eighty9nine/filament-excel-import#8]
Hi,

in production state of aplication I get error 401 Unauthorized while importing Excel documents. Can you help me find out what is the problem?

![Snimka zaslona 2024-01-17 160810](https://github.com/eighty9nine/filament-excel-import/assets/44787915/9ad9ce4b-cf39-4af4-a2ec-a29b34416df8)

**Comment by DiGiTransf** [comment]
Same issue here

![immagine](https://github.com/eighty9nine/filament-excel-import/assets/71734892/bdbcb618-caa1-4ab7-95d3-5f2486e712ee)

**Comment by DiGiTransf** [comment]
Same issue here:

![immagine](https://github.com/eighty9nine/filament-excel-import/assets/71734892/403c83fb-b927-4490-af84-e0c9b3f2b970)

**Comment by DiGiTransf** [comment]
May be useful a configuration item to manage temp upload folders

**Comment by DiGiTransf** [comment]
Update on this issue: I experience the "Error during upload" error if:
- I'm using _**Firefox**_ (**Edge or Chrome work fine**, even in https)
- I'm using **_Firefox via https_** connections (**http works**!)
Firefox tested with versions 115.11.0esr (64 bit) and 125.0.3 (64-bit), none works.

**Comment by DiGiTransf** [comment]
> May be useful a configuration item to manage temp upload folders

We set 'temporary_files' directive property 'local_path' to a custom (using an absolute path notation) writeable directory, in /config/excel.php but still no luck.

**Comment by eighty9nine** [comment]
In the new version, files wont persisted to disk unless specifically required by the dev. Hopefully this will fix the problem.

**Comment by abdrahmaan** [comment]
any updates or fix for this issue ?
